version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - gradle clean build
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/orderservice.jar
  discard-paths: yes